#!/bin/bash

# do nothing if on a fallback env
[ ! "$(/sbin/zfs mount | grep fallback)" ] || \
  { echo "befallback does not execute if a fallback boot environment is in use. Use beadm." ; exit; }

echo "destroying fallback.old ..."
yes | /usr/local/sbin/beadm destroy fallback.old
echo "renaming fallback to fallback.old"
/usr/local/sbin/beadm rename fallback fallback.old
echo "creating new fallback env ..."
/usr/local/sbin/beadm create fallback
echo "updating grub-menu..."
/usr/local/sbin/grubbe-mkconfig > /boot/grub/grub.cfg
echo "complete"
