#!/bin/bash
# beadm snap / grub menu rotator for cron
# https://github.com/a-schaefers/grubbe-mkconfig

# set a __unique__ BE name prefix
BE_PREFIX="snap_"

# set date format
DATE_FORMAT="$(date +%F_%H%M)"

# number of "snaps" to keep in rotation?
SAVE_NUMBER="3"

#################################################
#################################################

# sanity check
[ ! "$(/sbin/zfs mount | grep $BE_PREFIX)" ] || \
  { echo "For safety, besnap does not execute if the $BE_PREFIX prefixed boot environment is in use." | logger; exit; }

# get list of snaps
SNAP_LIST="$(/sbin/zfs list | grep "ROOT" | cut -d '/' -f 3 | cut -d ' ' -f 1 | sort | grep $BE_PREFIX)"

# count how many snaps we have
SNAP_NUM=$(echo "$SNAP_LIST" | grep "" -c)

# get oldest snap
SNAP_OLD=$(echo "$SNAP_LIST" | head -n 1)

# destroy oldest snap
if [ "$SNAP_NUM" -ge "$SAVE_NUMBER" ] ;
then
  yes | /usr/local/sbin/beadm destroy $SNAP_OLD
fi

# make a new snap
if [ "$SNAP_NUM" -le "$SAVE_NUMBER" ] ;
then
/usr/local/sbin/beadm create $BE_PREFIX$DATE_FORMAT
fi

# populate the boot loader
/usr/local/sbin/grubbe-mkconfig > /boot/grub/grub.cfg
