#!/bin/sh

# run ./grubbe-mkconfig > /boot/grub/grub.cfg
# Every time you beadm create, beadm rename, and beadm destroy

################
# pre-setup
################

# 0.0) GPT is assumed here.

# 0.1)
# in order to play nicely with boot environments, grub needs an unchanging location
# This is because grub stage1 is hardwired to find /boot/grub in the same dataset every time.
# I recommend /boot/grub is located on its own, separate dataset outside of ROOT.

# 0.2)
# This script assumes dracut was used for initramfs generation
# by using the root=zfs:pool/ROOT/BeName convention on linux cmdline
# if using genkernel or other, you will need to modify the line in the script:
# root=zfs:${POOL_NAME}/ROOT/$BENAME
# to use your required formatting for your system.

# 0.3)
# This script assumes a static (non-versioned) kernel naming convention.
# We need unchanging kernel and initramfs names in order to make this work.


################
# set variables
################

# set name of pool containing the ROOT dataset
POOL_NAME="zroot"

# set kernel name (e.g. for /boot/vmlinuz)
KERNEL="vmlinuz"

# set initramfs name (e.g. for /boot/initramfs.img)
INITRAMFS="initramfs.img"

# set kernel command line
CMDLINE="elevator=noop intel_iommu=on iommu=pt ipv6.disable=1 zfs.force=1"

# set root=''
# use grub-probe /boot/grub --target=bios_hints to see what should go here:
BIOS_HINTS="hd0,gpt1"


##############################################################################
##############################################################################

# get list of boot environments, one be per line
BELIST="$(zfs list | grep "ROOT" | cut -d '/' -f 3 | cut -d ' ' -f 1)"

#iterate over each line of the $BELIST, outputting our stanzas
IFS=$'\n'
for BENAME in $BELIST
do

cat <<EOF
menuentry '${BENAME}' {
	insmod gzio
	insmod part_gpt
	insmod zfs
	set root='${BIOS_HINTS}'
	echo	'Loading Linux ...'
	linux	/ROOT/${BENAME}@/boot/${KERNEL} root=zfs:${POOL_NAME}/ROOT/${BENAME} ${CMDLINE}
	echo	'Loading initial ramdisk ...'
	initrd	/ROOT/${BENAME}@/boot/${INITRAMFS}
    }
EOF

done
